### PR TITLE
Embeddings API `curl` usage

### PR DESCRIPTION
**Pull request by jamesbraza**
Upstreams knowledge from https://github.com/go-skynet/LocalAI/discussions/1089#discussioncomment-7074918 to the docs

### CODE REVIEW

**Review by lunamidori5 — CHANGES_REQUESTED** [review]
The model listed is wrong, you are trying to request the backend not the model it should be
 ``"model": "text-embedding-ada-002"``

**Comment by lunamidori5** [comment]
Github did not update, mergeing!

**Comment by jamesbraza** [comment]
Oh yeah, my bad there. I locally have `bert-embeddings` as the name per [this](https://localai.io/models/index.html).  Fixed to say `text-embedding-ada-002` 👌

**Comment by lunamidori5** [comment]
> Oh yeah, my bad there. I locally have `bert-embeddings` as the name per [this](https://localai.io/models/index.html). Fixed to say `text-embedding-ada-002` 👌

@jamesbraza thank you for pointing that out!

**Review by lunamidori5 — APPROVED** [review]

**Pull request merged**
