### PR TITLE
Add Bionic GPT project

### PR DESCRIPTION
**Pull request by ianpurton**

### CODE REVIEW

**Comment by lunamidori5** [comment]
Hello! How are you doing today?

I just wanted to know if you have documentation on how to use local ai on your application? If so would you be willing to link it here for review <3

**Comment by ianpurton** [comment]
@lunamidori5 Hi, we actually use local ai by default. 

We create our own Docker container based on the local ai container (as we include a model) here https://github.com/purton-tech/bionicgpt/blob/main/llm-docker/Dockerfile.localai

Then our docker-compose.yml uses that image see https://bionic-gpt.com/docs/running-locally/docker-compose/

**Review by lunamidori5 — COMMENTED** [review]
Alright Ill let @mudler have a look! 

Question from me, Why are you using the 1.22 image of Local Ai and not the 1.25? (This is just Luna asking, your merge will be Approved by Mudler soon!)

**Review by mudler — APPROVED** [review]

**Review by lunamidori5 — APPROVED** [review]

**Comment by ianpurton** [comment]
I'll look at 1.25, it might fix an issue I have anyway. Thanks.

**Comment by lunamidori5** [comment]
> I'll look at 1.25, it might fix an issue I have anyway. Thanks.

Ill go ahead and merge this then! Thank you for your time!

**Pull request merged**
