### PR TITLE
"How to Pages" fixes -Model Setup Fixes

### PR DESCRIPTION
**Pull request by lunamidori5**
- Added a notice on the gallery downloader page
- fixed the yaml file on both gallery and download page

### CODE REVIEW

**Review by Aisuko — COMMENTED** [review]
Hi @lunamidori5. Thanks for your contribution.  May you replace the PR's title to make sure it be more related to PR?

**Comment by lunamidori5** [comment]
> Hi @lunamidori5. Thanks for your contribution. May you replace the PR's title to make sure it be more related to PR?

@Aisuko it is about the How to changes to the site, it is already fitting to the fixes listed in the message on the PR, Unless I am confused on what this request is. Git will not let me change the title more than 50 chars so I am unable to put the changes in the title?

Deeply sorry for the confusion!

**Comment by Aisuko** [comment]
> > Hi @lunamidori5. Thanks for your contribution. May you replace the PR's title to make sure it be more related to PR?
> 
> @Aisuko it is about the How to changes to the site, it is already fitting to the fixes listed in the message on the PR, Unless I am confused on what this request is. Git will not let me change the title more than 50 chars so I am unable to put the changes in the title?
> 
> Deeply sorry for the confusion!

Thanks for your quick reply. Please do not be sorry with that. You can edit the PR title directly.

**Comment by lunamidori5** [comment]
> > > Hi @lunamidori5. Thanks for your contribution. May you replace the PR's title to make sure it be more related to PR?
> > 
> > 
> > @Aisuko it is about the How to changes to the site, it is already fitting to the fixes listed in the message on the PR, Unless I am confused on what this request is. Git will not let me change the title more than 50 chars so I am unable to put the changes in the title?
> > Deeply sorry for the confusion!
> 
> Thanks for your quick reply. Please do not be sorry with that. You can edit the PR title directly.

Already have edited to fit the changes to the how to pages

**Review by mudler — APPROVED** [review]

**Pull request merged**
